### ISSUE TITLE
语言文件lang.yml更改后重载生效，但重启后又会变为原始语言

### ISSUE THREAD

**Issue by Legendans** [SakuraTown/SakuraCDK#2]
作者你好，首先很喜欢你的这个CDK插件，功能非常全面，覆盖广泛
最近发现一个小问题，虽然不影响插件使用，但还是有一点困扰
大概就是，lang.yml更改语言配置，reload插件后可以立即生效，但服务器重启又会变成原始未更改的配置，
希望作者有时间可以修复一下，非常感谢！

**Comment by Iseason2000** [comment]
很抱歉现在才看到这个问题，在1.0.7修复了。
你可以加QQ群 887296263 以获得第一时间的反馈。
