### ISSUE TITLE
无法设置cdk

### ISSUE THREAD

**Issue by UPchonger** [SakuraTown/SakuraCDK#3]
作者你好！我曾经使用cdk.yml设置cdk时很简单就设置成功开始使用了！所以我非常喜欢这个插件(虽然没有使用执行指令的功能)
但是就在最近，我使用1.0.6版本创建cdk并且使用的时候，插件提示我cdk不存在或已过期，这是我的配置文件：kits.yml:ysfq:
    id: ysfq
    create: '2024-06-12T19:29:06.4963301'
    expires: '2044-06-12T19:29:06.4963301'
    itemStacks:
    - H4sIAAAAAAAA/41Rz2sTQRR+2eyGiGLT9qboyYMesrn4C2oPrcYSSGpJEIVcnE2G7TYzO+vs25B4kBZBsRXJQW9iPSj1UBA899Q/wD/Ak1hCLkrRi1ff5mcPFpzDvMfwzfe+7327P8EKNZxR2rWdqNHw0I7QE7an7HuaBQHXv1eWfvyaUZYBiSIkJQsQpoprrMlyMTBXYsFcKyCKKzUlbVcpV3CbWql8KkLwGtoFKSNkjuAEvlDh2mPCe8Trt5WWMDwGGFUwG7wdIsxWB/yC+W7ujrNGFHNVSDWZiHj4EB6D2QoiPYLZMcwewjpf7m9nwkvCAGgFRGsiGPPzSLUdcIRUnUnmUmNKjiyKuVID1PkjC/D8JvdR6bZdQC4ryGoNhGRpYYVcTk1GVlaVxtXStdnLD76WaTsVsPoSWxoyE9RyJB2un+6+Pnfy1betgS6z7wL6d3KswoqbNMKJWFt2IPhU3QsDwdpZn8lYtlCayvToldLI0pKVnpAgpGPVJeKI305TWvs79e7L7d6Ht73Pz3udJ+Ti6n9kVfRCPDasRBXSXHBJexonMpKQQDi7v+McrG8Oph7uveh2PnU3Px7ubRysb/3Tuzn0niznb5HNxeLdPIK1VM7nl4+mZN2MzZKB6cmCCz5yl+uZ7+/e/9l4dp20FUZBxD8z9DPqT7tI3Ztxd+MvLY8DuPoCAAA=cdk.yml:mapfenqiu:
  # normal 类型为 可重复多次使用的CDK，每人只能领取一次
  type: normal
  # 最大领取次数
  amount: 9999999
  # 过期时间
  expire: '2042-09-10T23:02:32.061'
  # 对应的礼包，可以多个
  kits:
  - ysfq我使用指令/cdk mapfenqiu他就提示我这个，我曾经也是这样设置的，但是这回却出现了问题，请问怎么解决呢？

**Comment by Iseason2000** [comment]
很抱歉现在才看到这个问题。
修改配置之后请执行 /cdkadmin update 将数据上传至数据库中才会生效
你可以加QQ群 887296263 以获得第一时间的反馈。

**Comment by UPchonger** [comment]
好的谢谢，作者我觉得你可以更新一下，让这个插件更容易使用，并且我推荐你把这个上传到minebbs,mcbbs不是似了吗

**Comment by Iseason2000** [comment]
刚刚更新了一次，有什么要求可以提出
